apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    io.rancher.container.pull_image: "true"
    io.rancher.container.start_once: "false"
    io.rancher.scheduler.affinity:container_label: io.rancher.stack_service.name=${stack_name}/hybris-retail-nrs-db
    io.rancher.scheduler.affinity:host_label: moon-pr=true
    io.rancher.scheduler.global: "false"
    kompose.cmd: kompose convert -f moon-compose
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: moon-utils
  name: moon-utils
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: moon-utils
    spec:
      containers:
      - env:
        - name: rancher_enabled
          value: "true"
        image: docker.nespresso.com/moon-utils:0.2.1-3
        name: moon-utils
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: moon-utils-claim0
      restartPolicy: Always
      volumes:
      - name: moon-utils-claim0
        persistentVolumeClaim:
          claimName: moon-utils-claim0
status: {}
