apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    io.rancher.scheduler.affinity:host_label: moon-pr=true
    kompose.cmd: kompose convert -f moon-compose
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: retail-app
  name: retail-app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: retail-app
    spec:
      containers:
      - image: docker.nespresso.com/moon/retail-app:8.160.1
        name: retail-app
        resources: {}
      restartPolicy: Always
status: {}
