apiVersion: v1
kind: ReplicaSet
metadata:
  name: nginx-rc
spec:
  replicas: 3
  selector: 
     app: nginx-app
  template:
     metadata: 
       name: nginx-pod
       labels: 
         app: nginx-app
     spec:
       containers: 
       - name: nginx-container
         image: nginx
         ports:
           - containerPort: 80

