apiVersion: v1
kind: Deployment
metadata:
   name: nginx-pod
   labels: 
      app: nginx
      tier: dev
            
spec:
   containers: 
   - name: nginx-container
     image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
        app: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80

