apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchExpressions:
      - {key: tier, operator: In, values: [Backend]}
      - {key: app, operator: NotIn, values: [stopped]}
  template:
    metadata:
      name: nginx-app
      labels:
        app: nginx-app
        tier: Backend
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.7.9
          ports:
          - containerPort: 80